check50:
  files:
    - !exclude "*"
    - !require "aliejus.cpp", "U1.txt", "U1rez.txt"
 
lab50:
  files:
    - !exclude "*"
    - !include "aliejus.cpp"

submit50:
  files:
    - !exclude "*"
    - !require "aliejus.cpp"
