check50:
  files:
    - !exclude "*"
    - !require "aliejus.cpp"
    - !require "U1.txt"
    - !require "U1rez.txt"
 
lab50:
  files:
    - !exclude "*"
    - !include "aliejus.cpp"

submit50:
  files:
    - !exclude "*"
    - !require "aliejus.cpp"
